version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  dagit:
    build: .
    command: dagit -f dag/job.py -h 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
